[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:gunicorn]
command=gunicorn matheusplintacom.wsgi:application --bind 127.0.0.1:9000 --workers 2 --threads 2 --timeout 30 --no-control-socket --access-logfile - --error-logfile -
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:caddy]
command=caddy run --config /app/docker/Caddyfile --adapter caddyfile
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
