# Generated by Django 6.0.5 on 2026-05-15 04:06

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', markdownx.models.MarkdownxField()),
                ('icon', models.CharField(blank=True, choices=[('icon-colts', 'Colts'), ('icon-byu', 'BYU')], max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('tag', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('tag-black', 'Black'), ('tag-blue', 'Blue'), ('tag-red', 'Red'), ('tag-orange', 'Orange')], default='tag-black', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', markdownx.models.MarkdownxField()),
                ('git_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tags', models.ManyToManyField(to='main.projecttag')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('icon-python', 'Python'), ('icon-node-js', 'NodeJS'), ('icon-react', 'React'), ('icon-docker', 'Docker'), ('icon-database', 'Database'), ('icon-microsoft', 'Microsoft'), ('icon-ubuntu', 'Ubuntu'), ('icon-github-alt', 'GitHub'), ('icon-aws', 'AWS')], max_length=100)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projecttag')),
            ],
        ),
    ]
