# Generated by Django 6.0.5 on 2026-06-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('icon-python', 'Python'), ('icon-node-js', 'NodeJS'), ('icon-react', 'React'), ('icon-docker', 'Docker'), ('icon-database', 'Database'), ('icon-microsoft', 'Microsoft'), ('icon-ubuntu', 'Ubuntu'), ('icon-github-alt', 'GitHub'), ('icon-aws', 'AWS'), ('icon-robot', 'AI')], max_length=100),
        ),
    ]
