# Generated by Codex on 2026-06-09

import django.db.models.deletion
from django.db import migrations, models


def copy_project_images(apps, schema_editor):
    Project = apps.get_model('main', 'Project')
    ProjectImage = apps.get_model('main', 'ProjectImage')

    for project in Project.objects.exclude(image=''):
        if project.image:
            ProjectImage.objects.get_or_create(
                project=project,
                image=project.image,
                defaults={
                    'alt_text': f'Image of {project.title}',
                    'order': 0,
                },
            )


def remove_copied_project_images(apps, schema_editor):
    ProjectImage = apps.get_model('main', 'ProjectImage')
    ProjectImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/projects/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RunPython(copy_project_images, remove_copied_project_images),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
